---
apiVersion: v1
kind: Service
metadata:
  name: medusa-storefront
  namespace: myapp
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: medusa-storefront
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: medusa-storefront
  namespace: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medusa-storefront
  template:
    metadata:
      labels:
        app: medusa-storefront
    spec:
      containers:
        - name: medusa-storefront
          image: myapp-storefront:latest
          imagePullPolicy: Never # 因为是本地镜像
          ports:
            - containerPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: medusa-storefront-ingress
  namespace: myapp
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: 'false' # 如果不需要 SSL
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
    - host: medusa.k8s.orb.local # 你可以修改这个域名
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: medusa-storefront
                port:
                  number: 80
