# .github/actions/update-gitops-config/action.yml
name: "Update GitOps Config"
description: "Updates image tags in GitOps configuration"

inputs:
  app:
    description: "Application name to update"
    required: true
  tag:
    description: "New image tag to set"
    required: true
  config-path:
    description: "Path to helm values file"
    default: "helm-charts/medusa/values.yaml"
  token:
    description: "GitHub token"
    required: true

runs:
  using: "composite"
  steps:
    - name: Update Image Tag
      shell: bash
      run: |
        echo "Updating ${{ inputs.app }} image tag to ${{ inputs.tag }}"

        # Update values.yaml using yq
        yq eval ".image.tag = \"${{ inputs.tag }}\"" -i ${{ inputs.config-path }}

        # Configure git with token-based authentication
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

        # Use token-based authentication
        git remote set-url origin https://x-access-token:${{ inputs.token }}@github.com/${{ github.repository }}.git

        git add ${{ inputs.config-path }}
        git commit -m "chore: update ${{ inputs.app }} image to ${{ inputs.tag }}"
        git push
