name: "Docker Build"
description: "Build and push Docker image"

inputs:
  app:
    description: "App name (storefront or medusa)"
    required: true
  GITHUB_TOKEN:
    description: "GitHub token for authentication"
    required: true
  DOCKER_REPOSITORY:
    description: "Docker repository name"
    required: true
  DOCKER_TAG:
    description: "Docker tag for the image"
    required: true
  DOCKER_REGISTRY:
    description: "Docker registry URL"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ inputs.DOCKER_REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ inputs.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./apps/${{ inputs.app }}/Dockerfile
        push: true
        tags: ${{ inputs.DOCKER_REPOSITORY }}:${{ inputs.DOCKER_TAG }}
