version: '3'
services:
  db:
    image: postgres:16
    container_name: medusa-starter-postgres
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'postgres'
  redis:
    image: redis
    container_name: medusa-starter-redis
    ports:
      - '6379:6379'
    volumes:
      - redis:/data
  # meilisearch:
  #   image: getmeili/meilisearch:v1.11
  #   ports:
  #     - "7700:7700"
  #   environment:
  #     - MEILI_MASTER_KEY=MASTER_KEY # 修改为你的密钥
  #   volumes:
  #     - meilisearch_data:/meili_data

volumes:
  database:
  redis:
  # meilisearch_data:
