name: Backend CI

on:
  repository_dispatch:
    types: [backend-build]
  push:
    paths:
      - 'apps/backend/**'
      - 'packages/**'
    branches:
      - 'feature/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # 使用现有的 monorepo-install action
      - name: Setup Dependencies
        uses: ./.github/actions/monorepo-install
        with:
          cache-node-modules: 'true'
          cache-install-state: 'true'
          enable-corepack: 'true'
      
      # Turbo 缓存
      - name: Setup Turbo Cache
        uses: actions/cache@v4
        with:
          path: node_modules/.cache/turbo
          key: turbo-backend-${{ github.sha }}
          restore-keys: |
            turbo-backend-
      
      # 构建和测试
      - name: Build and Test
        run: yarn turbo run build test --filter=backend...
      
      # Docker 构建和推送
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      
      - name: Build and Push Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./apps/backend/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/backend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      # 更新 GitOps 配置
      - name: Update GitOps Config
        uses: ./.github/actions/update-gitops-config
        with:
          app: backend
          tag: ${{ github.sha }}