name: Deploy
on:
  push:
    branches:
      - main

env:
  DEPLOY_ENV: ${{ github.ref == 'refs/heads/main' && 'production' || 'local' }}

jobs:
  setup:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: ./.github/actions/monorepo-install
      - uses: dtinth/setup-github-actions-caching-for-turbo@v1
      - run: yarn build

  deploy:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [storefront, medusa]
    steps:
      - uses: actions/checkout@v4
      
      - name: Load deploy config
        id: config
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const yaml = require('js-yaml');
            const fs = require('fs');
            const config = yaml.load(fs.readFileSync('deploy-config.yml', 'utf8'));
            const env = process.env.DEPLOY_ENV;
            const appConfig = config.environments[env];
            
            return JSON.stringify({
              docker: {
                registry: appConfig.docker.registry,
                repository: `${appConfig.docker.registry}/${appConfig.docker.repositories['${{ matrix.app }}']}`,
                tag: process.env.GITHUB_SHA || 'latest'
              },
              k8s: {
                namespace: appConfig.kubernetes.namespace,
                context: appConfig.kubernetes.context
              }
            });

      - name: Build and push Docker image
        uses: ./.github/actions/docker
        with:
          app: ${{ matrix.app }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_REPOSITORY: ${{ fromJSON(steps.config.outputs.result).docker.repository }}
          DOCKER_TAG: ${{ fromJSON(steps.config.outputs.result).docker.tag }}
          DOCKER_REGISTRY: ${{ fromJSON(steps.config.outputs.result).docker.registry }}

      - name: Deploy to Kubernetes
        uses: WyriHaximus/github-action-helm3@v2
        env:
          HELM_NAME: ${{ matrix.app }}
          KUBE_NAMESPACE: ${{ fromJSON(steps.config.outputs.result).k8s.namespace }}
          KUBE_CONTEXT: ${{ fromJSON(steps.config.outputs.result).k8s.context }}
        with:
          exec: |
            helm upgrade ${HELM_NAME} --reuse-values \
            --set image.tag=${{ fromJSON(steps.config.outputs.result).docker.tag }} \
            --set image.repository=${{ fromJSON(steps.config.outputs.result).docker.repository }} \
            ./helm-charts/${{ matrix.app }}/ -n ${KUBE_NAMESPACE} \
            --kube-context ${KUBE_CONTEXT}
          kubeconfig: ${{ secrets.EKS_KUBECONFIG }}